version: '3.8'

services:
  neo4j:
    hostname: neo4j
    container_name: neo4j
    image: neo4j:latest
    user: 1000:1000
    networks:
      - neo4j-network
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    environment:
      - NEO4J_AUTH=neo4j/test12345678
      - NEO4JLABS_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
    volumes:
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import

  neo4japp:
    image: php:8.1-cli
    networks:
      - neo4j-network
    container_name: neo4japp
    working_dir: /var/www/html
    volumes:
      - "./:/var/www/html:cached"
    ports:
      - "80:80"
    depends_on:
      - neo4j

networks:
  neo4j-network:
    driver: bridge

